package assets

var QUOTES_GOKU = []string{
	"Heh heh, it sure is exciting fighting strong opponents like you!",
	"Keep training and get stronger... I'll always be one step ahead of you, though!",
	"Low-ranker, elite, whatever. You can beat anyone...it's called hard work!",
	"You're really strong... I wanna fight you again!",
	"Uh-oh! I think I got carried away!",
	"I don't know why you're fighting by my side, but no more body-swapping, okay? That was weird.",
	"You try and one-up me sometimes, but I'm not gonna let you get the upper hand anytime soon!",
	"I'm gonna fight you with everything I've got!",
	"Show me what you can do!",
	"I'm Goku, a Saiyan who was raised on Earth...or so they tell me.",
	"You aren't strong enough to beat me. I can tell that without even fighting you.",
	"Heh heh... Fighting you never fails to give me goosebumps.",
	"You look kinda familiar!",
	"Power comes in response to a need, not a desire.",
	"I am the hope of the universe...I am the answer to all living things that cry out for peace...I am the protector of the innocent...I am the light in the darkness...I am truth. Ally to good...Nightmare to you!",
	"Well, if your friend is stronger than you, I guess you’re the third strongest Saiyan now.",
	"It looks like they only want me, and that’s exactly who they’ll get.",
	"Show them what a Saiyan is made of!",
	"With my new found power, I can beat anyone!",
	"I am going to be a lot stronger than I ever was!",
	"Maybe you’ll come back someday as…as a better person, I hope. I’d like that. Perhaps we’ll have a little one on one.",
	"Sometimes life is too uncertain to have regrets.",
	"I would rather be a brainless monkey than a heartless monster.",
	"An angel? So Whis is an angel? But he’s got no wings, and his butt’s not hanging out.",
	"The ocean is so salty because everyone pees in it.",
	"It would be meaningless to fight with you now. You’re too scared and ashamed. Live with the shock. Keep it bottled up inside you. Silently.",
	"I’m so hungry, I can’t even move.",
	"How can androids have babies?",
}
